{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "sonarqube.fullname" . }}
  labels:
    app: {{ template "sonarqube.name" . }}
    chart: {{ template "sonarqube.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if .Values.route.hostname }}
  host: {{ .Values.route.hostname }}
  {{- end }}
  path: {{ .Values.contextPath }}
  port:
    targetPort: http
  {{- if .Values.route.tls }}
  tls:
  {{ toYaml .Values.route.tls | indent 2 }}
  {{- end }}
  to:
    kind: Service
    name: {{ template "sonarqube.fullname" . }}
    weight: 100
  wildcardPolicy: None
{{- end -}}
