apiVersion: v1
kind: Secret
metadata:
  name: {{ template "activemq.fullname" . }}
  labels:
    app: {{ template "activemq.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  activemq.username: {{ .Values.secrets.authentication.username | b64enc }}
  activemq.password: {{ .Values.secrets.authentication.password | b64enc }}
  broker.ks: >-
    {{ .Values.secrets.ssl.broker.ks.file }}
  activemq.keystore.password: {{ .Values.secrets.ssl.broker.ks.password | b64enc }}
  broker.ts: >-
    {{ .Values.secrets.ssl.broker.ts.file }}
  activemq.truststore.password: {{ .Values.secrets.ssl.broker.ts.password | b64enc }}
