apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "activemq.name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "activemq.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "activemq.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "activemq.name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ template "activemq.name" . }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - pods
  - replicationcontrollers
  - services
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - bindings
  - events
  - limitranges
  - namespaces
  - namespaces/status
  - pods/log
  - pods/status
  - replicationcontrollers/status
  - resourcequotas
  - resourcequotas/status
  verbs:
  - get
  - list
- apiGroups:
  - "autoscaling"
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
- apiGroups:
  - "extensions"
  resources:
  - deployments
  - deployments/scale
  - horizontalpodautoscalers
  - replicasets
  - replicasets/scale
  verbs:
  - get
  - list
- apiGroups:
  - "apps"
  resources:
  - deployments
  - deployments/scale
  - statefulsets
  verbs:
  - get
  - list
- apiGroups:
  - "apps.openshift.io"
  resources:
  - deploymentconfigs
  - deploymentconfigs/scale
  verbs:
  - get
  - list
- apiGroups:
  - "apps.openshift.io"
  resources:
  - deploymentconfigs/log
  - deploymentconfigs/status
  verbs:
  - get
  - list