apiVersion: v1
kind: Service
metadata:
  name: {{ template "activemq.fullname" . }}-amq-amqp-ssl
  labels:
    app: {{ template "activemq.name" . }}
    chart: {{ template "activemq.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.amqp.ssl.type }}
  ports:
    - port: {{ .Values.service.amqp.ssl.port }}
      targetPort: {{ .Values.service.amqp.ssl.port }}
      protocol: TCP
      name: amq-amqp-ssl
  selector:
    app: {{ template "activemq.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "activemq.fullname" . }}-amq-mqtt-ssl
  labels:
    app: {{ template "activemq.name" . }}
    chart: {{ template "activemq.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.mqtt.ssl.type }}
  ports:
    - port: {{ .Values.service.mqtt.ssl.port }}
      targetPort: {{ .Values.service.mqtt.ssl.port }}
      protocol: TCP
      name: amq-mqtt-ssl
  selector:
    app: {{ template "activemq.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "activemq.fullname" . }}-amq-stomp-ssl
  labels:
    app: {{ template "activemq.name" . }}
    chart: {{ template "activemq.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.stomp.ssl.type }}
  ports:
    - port: {{ .Values.service.stomp.ssl.port }}
      targetPort: {{ .Values.service.stomp.ssl.port }}
      protocol: TCP
      name: amq-stomp-ssl
  selector:
    app: {{ template "activemq.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "activemq.fullname" . }}-amq-tcp-ssl
  labels:
    app: {{ template "activemq.name" . }}
    chart: {{ template "activemq.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.tcp.ssl.type }}
  ports:
    - port: {{ .Values.service.tcp.ssl.port }}
      targetPort: {{ .Values.service.tcp.ssl.port }}
      protocol: TCP
      name: amq-tcp-ssl
  selector:
    app: {{ template "activemq.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "activemq.fullname" . }}-amq-mesh
  labels:
    app: {{ template "activemq.name" . }}
    chart: {{ template "activemq.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: 'true'
    description: Supports node discovery for mesh formation.
spec:
  clusterIP: None
  type: {{ .Values.service.mesh.type }}
  ports:
    - port: {{ .Values.service.mesh.port }}
      targetPort: {{ .Values.service.mesh.port }}
      protocol: TCP
      name: amq-mesh
  selector:
    app: {{ template "activemq.name" . }}
    release: {{ .Release.Name }}
