apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "activemq.name" . }}
spec:
 storageClassName: {{ .Values.storage.className | quote }}
 accessModes:
    - {{ .Values.storage.accessMode | quote }}
 resources:
   requests:
    storage: {{ .Values.storage.capacity | quote }}
